# # Create value file for ArgoCD
# global:
#   tolerations:
#   - key: "CriticalAddonsOnly"
#     operator: "Exists"
# controller:
#   env:
#     - name: ARGOCD_SYNC_WAVE_DELAY
#       value: '30'
# configs:
#   cm:
#     ui.bannercontent: "Management Environment"
#   params:
#     server.insecure: true
#     server.basehref: /proxy/8081/
